### ISSUE TITLE
[CHALBUG] know_your_mem

### ISSUE THREAD

**Issue by algoatson** [o-o-overflow/archiveooo#42]
Challenge URL: https://archive.ooo/c/know_your_mem/359/

know_your_mem seems to have a problem that it didn't had before ? it now tries to open "./flag" instead of "./flag.txt" but the error message mentions that it's trying to open "./flag.txt", also the challenge on the sites comes with a file `flag.txt`, not `flag`. (note i am talking about the docker instance, by following the steps for docker on the site.)

i'm not sure if i'm insane or this is wrong, anyway just wanted to let ya guys know.

**Comment by Jacopo** [comment]
Hi, thanks for the report! You are definitely not insane :D 
It seems the docker container we uploaded does not contain the /flag file. It should have been injected during the container build but we may have missed this step. I also confirm that the "flag.txt" error message is a mistake, the file is actually just named "flag". Apologies for the confusion.

I'll look into it: since we're retired from organizing the archive is in maintenance-mode but I should fix this.

In the meantime, what I'd recommend is checking out [the source code](https://github.com/o-o-overflow/dc2019q-know_your_mem/tree/v1/service/src) and running `make mycheck`. That will compile the service and verify that the reference solution works: if that completes successfully then you're all set.

Alternatively, `echo 'OOO{somethingsomething}' > flag` and `docker cp flag THE_CONTAINER:/flag` should make the local container work. The website version should work correctly too.

**Comment by algoatson** [comment]
Thanks !! ahahah :D
